version: '3.8'

services:
  satriadivo-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: satriadivo-portfolio
    restart: always
    ports:
      - "3000:80" # Expose port 3000 di VPS -> port 80 di Nginx container
