version: '3.8'

services:
  portofolio-builder:
    context: ./D:/Belajar/Projek/portofolio
    build: .
    stage: builder
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - DISABLE_HMR=true

  portofolio-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf