version: '3.8'

services:
  portfolio:
    # Membangun image dari Dockerfile di direktori saat ini
    build: 
      context: .
      dockerfile: Dockerfile
    
    # Nama image dan container
    image: satriadivo/portfolio:latest
    container_name: dev_portfolio
    
    # Port mapping: host_port:container_port
    # Nginx di dalam container mengekspos port 80
    ports:
      - "8080:80"
    
    # Supaya otomatis restart kalau VPS/Server reboot
    restart: unless-stopped
